services:
  # uncomment these to use on development
  # postgres-dev:
  #   env_file: .env.development
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   ports:
  #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}  -p ${POSTGRES_PORT}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  postgres:
    env_file:
      - path: .env
        required: false
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}  -p ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - path: .env
        required: false
    image: filkomunklab/filkom-apps-be:latest
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_dev_data:
