services:
  postgres:
    env_file: .env
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}  -p ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file: .env
    image: filkomunklab/filkom-apps-be:latest
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

volumes:
  postgres_data:
