services:
  dev-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_USER="postgres"
      - POSTGRES_DB="dev"

  test-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    env_file: ".env.test"

volumes:
  postgres_data:
