version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: filkomapp@unklab
      POSTGRES_PASSWORD: ifT7CLv5xZZLz10
      POSTGRES_DB: filkomapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
