version: "3"
services:
  dev-db:
    image: postgres:latest
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_USER="postgres"
      - POSTGRES_DB="dev"

volumes:
  postgres_data:
