version: "3"
services:
  app:
    depends_on:
      - postgres
    image: darellyuhu/filkomapp-be
    ports:
      - "3000:3000"
    command: /bin/sh -c "npm install && npm start"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
