name: Deploy to Artifact Registry and Cloud Run
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{secrets.SERVICE_ACCOUNT_KEY}}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: filkom-unklab

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Build Docker Image
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
          docker build -t asia-southeast1-docker.pkg.dev/filkom-unklab/filkom-app-api/main:latest .

      - name: Push Docker Image
        run: docker push asia-southeast1-docker.pkg.dev/filkom-unklab/filkom-app-api/main:latest
