name: Idcloudhost production CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: darellyuhu/filkomapp-be
          tags: latest
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: darellyuhu/filkomapp-be:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose.yml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: docker-compose.yml
          target: ~/

      - name: SSH and run deploy docker compose script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            touch .env
            echo POSTGRES_USER=${{secrets.POSTGRES_USER}} >> .env
            echo POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} >> .env
            echo POSTGRES_DB=${{secrets.POSTGRES_DB}} >> .env
            echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker compose pull
            docker compose up -d
            cat .env
            rm .env

      # - name: Deploy to Docker swarm
      #   uses: wshihadeh/docker-deployment-action@v1
      #   with:
      #     remote_docker_host: ${{ secrets.SERVER_HOST }}
      #     ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.SERVER_PUBLIC_KEY }}
      #     stack_file_name: docker-compose.yml
      #     args: filkomapp

      # - name: Deploy into server
      #   uses: astappiev/docker-compose-remote-action@master
      #   with:
      #     ssh_host: ${{ secrets.SERVER_HOST }}
      #     ssh_user: ${{ secrets.SERVER_USERNAME }}
      #     ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
      #     ssh_host_public_key: ${{ secrets.SERVER_PUBLIC_KEY }}
      #     ssh_jump_public_key: ${{ secrets.SERVER_JUMP_PUBLIC_KEY }}
      #     docker_compose_prefix: filkomapp
