name: Idcloudhost production CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t darellyuhu/filkom-app-be .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push darellyuhu/filkom-app-be

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop filkomapp || true
            docker rm filkomapp || true
            docker pull darellyuhu/filkom-app-be
            docker run -d --name filkomapp -p 3000:3000 darellyuhu/filkom-app-be
